Employee Info/EmployeeInfo/EmployeeInfo/Models/DbModels.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeInfo.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }
        [Required, Display(Name = "Department Name"), StringLength(75)]
        public string DepartmentName { get; set; }
        //Nev
        public virtual ICollection<Employee> Employees { get; set; }
    }

    public class Employee
    {
        public int EmployeeId { get; set; }
        [Required, Display(Name ="Employee Name"), StringLength(75)]
        public string EmployeeName { get; set; }
        [Required, Column(TypeName = "date"), Display(Name = "Date Of Birth"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DOB { get; set; }
        [Required, Display(Name = "Email"), StringLength(30)]
        public string Email { get; set; }
        [Required, Display(Name = "Phone"), StringLength(15)]
        public string Phone { get; set; }
        [Display(Name = "Image")]
        public string PicturePath { get; set; }
        // Nev
        public virtual Department Department { get; set; }
    }

    public class EmployeeDbContext : DbContext
    {
        public EmployeeDbContext(DbContextOptions<EmployeeDbContext> options) : base(options) { }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
    }

}

Employee Info/EmployeeInfo/EmployeeInfo/Models/EmployeeVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeInfo.Models
{
    public class EmployeeVM
    {
        public int EmployeeId { get; set; }
        [Required, Display(Name = "Employee Name"), StringLength(75)]
        public string EmployeeName { get; set; }
        [Required, Column(TypeName = "date"), Display(Name = "Date Of Birth"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DOB { get; set; }
        [Required, Display(Name = "Email"), StringLength(30)]
        public string Email { get; set; }
        [Required, Display(Name = "Phone"), StringLength(15)]
        public string Phone { get; set; }
        [Display(Name = "Department")]
        public int DepartmentId { get; set; }
        [Display(Name = "Image")]
        public string PicturePath { get; set; }
        public IFormFile Pictures { get; set; }
    }
}

Employee Info/EmployeeInfo/EmployeeInfo/Models/ErrorViewModel.cs
using System;

namespace EmployeeInfo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employee Info/EmployeeInfo/EmployeeInfo/Controllers/EmployeeController.cs
using EmployeeInfo.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeInfo.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EmployeeDbContext db;
        private readonly IWebHostEnvironment _hostEnv;
        public EmployeeController(EmployeeDbContext db, IWebHostEnvironment hostEnv)
        {
            this.db = db;
            this._hostEnv = hostEnv;
        }

        public IActionResult Index()
        {
            ViewBag.departments = db.Departments.ToList();
            return View(db.Employees.ToList());
        }

        public IActionResult Create()
        {
            ViewBag.departments = db.Departments.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeeVM evm)
        {
            if (ModelState.IsValid)
            {
                if (evm.Pictures !=null)
                {
                    string newFileName = Guid.NewGuid().ToString() + "_" + evm.Pictures.FileName;
                    string newFilePath = Path.Combine("Images", newFileName);
                    string file = Path.Combine(_hostEnv.WebRootPath, newFilePath);
                    evm.Pictures.CopyTo(new FileStream(file, FileMode.Create));

                    Employee emp = new Employee
                    {
                        EmployeeName = evm.EmployeeName,
                        DOB = evm.DOB,
                        Email =evm.Email,
                        Phone =evm.Phone,
                        PicturePath = newFileName
                    };
                    db.Employees.Add(emp);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }

            ViewBag.departments = db.Departments.ToList();
            return View();
        }

    }
}

Employee Info/EmployeeInfo/EmployeeInfo/Controllers/HomeController.cs
using EmployeeInfo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeInfo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employee Info/EmployeeInfo/EmployeeInfo/Views/Employee/Create.cshtml
@model EmployeeInfo.Models.EmployeeVM
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col">
        <h2>Add New Car</h2>
        <div id="panel"></div>
        <form id="frmCreate"
              asp-action="Create"
              asp-controller="Employee"
              data-ajax-method="Post"
              data-ajax="true"
              data-ajax-mode="replace"
              data-ajax-update="#panel"
              data-ajax-success="success">
            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="EmployeeName">@Html.DisplayNameFor(x => x.EmployeeName)</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" asp-for="EmployeeName" />
                </div>
                <div class="col-4">
                    <span asp-validation-for="EmployeeName" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="DOB">@Html.DisplayNameFor(x => x.DOB)</label>
                <div class="col-md-6">
                    <input class="form-control" type="date" asp-for="DOB" />
                </div>
                <div class="col-4">
                    <span asp-validation-for="DOB" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="Email">@Html.DisplayNameFor(x => x.Email)</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" asp-for="Email" />
                </div>
                <div class="col-4">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="Phone">@Html.DisplayNameFor(x => x.Phone)</label>
                <div class="col-md-6">
                    <input class="form-control" type="text" asp-for="Phone" />
                </div>
                <div class="col-4">
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="DepartmentId">@Html.DisplayNameFor(x => x.DepartmentId)</label>
                <div class="col-md-6">
                    <select class="form-control" asp-for="DepartmentId" asp-items="@(new SelectList(ViewBag.departments,"DepartmentId","DepartmentName"))">
                        <option value="0" selected="selected">----Select-----</option>
                    </select>
                </div>
                <div class="col-4">
                    <span asp-validation-for="DepartmentId" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-2">
                <label class="col-form-label col-2" asp-for="Pictures">@Html.DisplayNameFor(x => x.Pictures)</label>
                <div class="col-md-6">
                    <input type="file" class="form-control" asp-for="Pictures" />
                </div>
                <div class="col-4">
                    <span asp-validation-for="Pictures" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>

        </form>
    </div>
</div>




@section scripts{
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @*<script src="~/lib/ajax/dist/jquery.unobtrusive-ajax.js"></script>*@
    <script type="text/javascript">
        $("#frmCreate").attr("enctype", "multipart/form-data")
        function success() {
            $("#frmCreate").trigger('reset')
        }
    </script>
}

Employee Info/EmployeeInfo/EmployeeInfo/Views/Employee/Index.cshtml
@model IEnumerable<EmployeeInfo.Models.Employee>
@{
    ViewData["Title"] = "Index";
}


<div class="row">
    <div class="col">
        <h2>Employee List</h2>
        <div class="d-flex justify-content-end">
            <a class="btn btn-outline-primary" asp-action="Create" asp-controller="Employee">Add New</a>
        </div>
        <table class="table table-bordered table-sm table-striped mt-2">
            <thead class="table-warning">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.EmployeeName)</th>
                    <th>@Html.DisplayNameFor(x => x.DOB)</th>
                    <th>@Html.DisplayNameFor(x => x.Email)</th>
                    <th>@Html.DisplayNameFor(x => x.Phone)</th>
                    <th>@Html.DisplayNameFor(x => x.Department.DepartmentName)</th>
                    <th>@Html.DisplayNameFor(x => x.PicturePath)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@Html.DisplayFor(x => item.EmployeeName)</td>

                    <td>@Html.DisplayFor(x => item.DOB)</td>
                    <td>@Html.DisplayFor(x => item.Email)</td>
                    <td>@Html.DisplayFor(x => item.Phone)</td>
                    <td>@Html.DisplayFor(x => item.Department.DepartmentName)</td>
                    <td>
                        <img src="~/Images/@item.PicturePath" alt="Photo of @item.EmployeeName" width="40" />
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="Home" asp-route-id="@item.EmployeeId" class="btn btn-outline-success btn-sm">Edit</a>
                        <a asp-action="Delete" asp-controller="Home" asp-route-id="@item.EmployeeId" class="btn btn-outline-danger btn-sm">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Employee Info/EmployeeInfo/EmployeeInfo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employee Info/EmployeeInfo/EmployeeInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeInfo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeInfo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeeInfo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>